In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [3]:
#Create my dataframe with imbalanced dataset

class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [7]:
df = pd.concat([class_0, class_1], ignore_index=True)
df.tail()

     feature1  feature2  target
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

UP-SAMPLING

In [9]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [14]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Users/vinaykarakavalasa/Machine Learning/.venv/lib/python3.14/site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 16.6 MB/s  0:00:00 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 17.7 MB/s  0:00:01 eta 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [15]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority, 
                                 replace=True, 
                                 n_samples=len(df_majority), 
                                 random_state=123)

In [16]:
df_minority_upsampled.shape

(900, 3)

In [18]:
df_minority_upsampled.tail(20)

     feature1  feature2  target
954  1.487494  3.310876       1
952  1.188902  2.189189       1
947  1.402209  2.775845       1
966  0.671933  1.370988       1
954  1.487494  3.310876       1
931  2.540392  3.092068       1
957  1.364350  1.535966       1
977  3.167991  2.822218       1
989  3.013493  2.047240       1
968  2.272462  2.493580       1
927  3.382173  2.913005       1
971  2.272825  3.034197       1
996  2.239810  0.880077       1
999  2.697490  2.013570       1
959  0.666001  1.894732       1
912  2.834499  2.773754       1
983  2.844335  2.015572       1
917  2.197269  4.216788       1
950  2.399896 -0.840847       1
949  2.944820  1.277924       1

In [19]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled], ignore_index=True)
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

DOWNSAMPLING

In [20]:
#Create my dataframe with imbalanced dataset

class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [21]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [22]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority, 
                                   replace=False, 
                                   n_samples=len(df_minority), 
                                   random_state=123)

In [23]:
df_majority_downsampled.shape

(100, 3)

In [24]:
df_majority_downsampled.head()

     feature1  feature2  target
613 -1.147525  0.284447       0
524 -0.448392  0.777222       0
690 -1.576233  0.187258       0
457  1.601908 -1.080462       0
85  -1.085902 -1.775243       0